language: node_js
sudo: false
node_js:
  - "stable"

env:
  global:
    - CC_TEST_REPORTER_ID=60d2e3d3908a8dd4f8758139083b1f1fb88cd8e4ff6132aa7a4c7b70a209296d
      NODE_ENV=test

script:
  - npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info