language: node_js
sudo: false
node_js:
  - "stable"
addons:
    code_climate:
        repo_token: 60d2e3d3908a8dd4f8758139083b1f1fb88cd8e4ff6132aa7a4c7b70a209296d
# script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
env:
  global:
    - CC_TEST_REPORTER_ID=60d2e3d3908a8dd4f8758139083b1f1fb88cd8e4ff6132aa7a4c7b70a209296d
script:
  - npm test

after_success:
- npm run coveralls